<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.2.0</Version>
        <Authors>TuiHub</Authors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.2.0"/>
        <PackageReference Include="Grpc.AspNetCore" Version="2.80.0"/>
        <PackageReference Include="Grpc.AspNetCore.Web" Version="2.80.0"/>
        <PackageReference Include="Grpc.Net.Client" Version="2.80.0"/>
        <PackageReference Include="Grpc.Tools" Version="2.81.1" PrivateAssets="All"/>
        <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="8.0.28"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9"/>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos\*.proto" GrpcServices="Server" ProtoRoot="Protos"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Librarian.Common\Librarian.Common.csproj"/>
    </ItemGroup>

</Project>
