// <auto-generated />
using System;
using Librarian.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Librarian.Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AppAppCategory", b =>
                {
                    b.Property<long>("AppCategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppCategoriesId", "AppsId");

                    b.HasIndex("AppsId");

                    b.ToTable("AppAppCategory");
                });

            modelBuilder.Entity("DeviceUser", b =>
                {
                    b.Property<long>("DevicesId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DevicesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("DeviceUser");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Account", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformAccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("Platform", "PlatformAccountId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.App", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AltNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("AppInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppSources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BackgroundImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("BoundStoreAppId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CoverImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatorDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("IconImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RevisedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("RevisedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopStoreManage")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalAppSaveFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalAppSaveFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TotalRunTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppInfoId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsPublic");

                    b.HasIndex("Name");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Apps");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppCategory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AppCategories");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AltNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BackgroundImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("CoverImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("IconImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAppId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("Source", "SourceAppId");

                    b.ToTable("AppInfos");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppRunTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("StartDateTime", "EndDateTime");

                    b.ToTable("AppRunTimes");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppSaveFile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileMetadataId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FileMetadataId");

                    b.HasIndex("IsPinned");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("AppSaveFiles");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppSaveFileCapacity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EntityInternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strategy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityInternalId");

                    b.ToTable("AppSaveFileCapacities");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Device", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSourceCodeAddress")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemVersion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceName");

                    b.HasIndex("SystemType");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeatureFlag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJsonSchema")
                        .IsRequired()
                        .HasMaxLength(65535)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdStr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireContext")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IdStr")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeatureRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasMaxLength(65535)
                        .HasColumnType("TEXT");

                    b.Property<long>("ContextId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FeatureFlagId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdStr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FeatureFlagId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("FeatureRequests");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeedActionSet", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<long>("FeedConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FeedConfigId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("FeedActions");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeedConfig", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<long>("FeedItemCollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPullMessage")
                        .HasMaxLength(65535)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastPullStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPullTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PullInterval")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FeedItemCollectionId");

                    b.HasIndex("SourceId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("FeedConfigs");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeedItemCollection", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryStr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryStr")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("FeedItemCollections");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FileMetadata", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("BLOB")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("SizeBytes");

                    b.HasIndex("Type");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("FileMetadatas");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Porter", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextJsonSchema")
                        .HasMaxLength(65535)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureSummary")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PorterContextId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GlobalName")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Porters");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.PorterContext", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasMaxLength(65535)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("PorterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PorterId")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("PorterContexts");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Sentinel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AltUrls")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadFileUrlPath")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("TEXT");

                    b.Property<string>("GetTokenUrlPath")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Sentinels");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.SentinelAppBinary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChunksInfo")
                        .IsRequired()
                        .HasMaxLength(65535)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedToken")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("SentinelLibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("SentinelLibraryId", "GeneratedId")
                        .IsUnique();

                    b.ToTable("SentinelAppBinaries");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.SentinelLibrary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadBasePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SentinelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SentinelId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("SentinelLibraries");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("InternalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TokenJti")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ExpiredAt");

                    b.HasIndex("InternalId");

                    b.HasIndex("Status");

                    b.HasIndex("TokenJti");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.StoreApp", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("AltNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppSources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BackgroundImageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CoverImageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("IconImageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StoreApps");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.StoreAppBinary", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AppInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SentinelGeneratedId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("SentinelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoreAppId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppInfoId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SentinelGeneratedId");

                    b.HasIndex("StoreAppId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("StoreAppBinaries");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppAppSaveFileCapacityCountDefault")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AppAppSaveFileCapacitySizeBytesDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppAppSaveFileCapacityStrategyDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalAppSaveFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalAppSaveFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppAppCategory", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.AppCategory", null)
                        .WithMany()
                        .HasForeignKey("AppCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Common.Models.Db.App", null)
                        .WithMany()
                        .HasForeignKey("AppsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeviceUser", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.Device", null)
                        .WithMany()
                        .HasForeignKey("DevicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Common.Models.Db.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Account", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.App", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.AppInfo", "AppInfo")
                        .WithMany()
                        .HasForeignKey("AppInfoId");

                    b.HasOne("Librarian.Common.Models.Db.User", "User")
                        .WithMany("Apps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppCategory", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.User", "User")
                        .WithMany("AppCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppInfo", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.Account", "Account")
                        .WithMany("AppInfos")
                        .HasForeignKey("AccountId");

                    b.HasOne("Librarian.Common.Models.Db.User", "User")
                        .WithMany("AppInfos")
                        .HasForeignKey("UserId");

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppRunTime", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.App", "App")
                        .WithMany("AppRunTimes")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Common.Models.Db.Device", "Device")
                        .WithMany("AppRunTimes")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppSaveFile", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.App", "App")
                        .WithMany("AppSaveFiles")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Common.Models.Db.FileMetadata", "FileMetadata")
                        .WithMany()
                        .HasForeignKey("FileMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("FileMetadata");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppSaveFileCapacity", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.User", "User")
                        .WithMany("AppSaveFileCapacities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeatureRequest", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.FeatureFlag", "FeatureFlag")
                        .WithMany()
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeedActionSet", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.FeedConfig", "FeedConfig")
                        .WithMany("FeedActionSets")
                        .HasForeignKey("FeedConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedConfig");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeedConfig", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.FeedItemCollection", "FeedItemCollection")
                        .WithMany("FeedConfigs")
                        .HasForeignKey("FeedItemCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Common.Models.Db.FeatureRequest", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedItemCollection");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.PorterContext", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.Porter", "Porter")
                        .WithOne("PorterContext")
                        .HasForeignKey("Librarian.Common.Models.Db.PorterContext", "PorterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Porter");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Sentinel", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.User", "User")
                        .WithMany("Sentinels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.SentinelAppBinary", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.SentinelLibrary", "SentinelLibrary")
                        .WithMany("AppBinaries")
                        .HasForeignKey("SentinelLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SentinelLibrary");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.SentinelLibrary", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.Sentinel", "Sentinel")
                        .WithMany("SentinelLibraries")
                        .HasForeignKey("SentinelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sentinel");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Session", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Librarian.Common.Models.Db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.StoreAppBinary", b =>
                {
                    b.HasOne("Librarian.Common.Models.Db.AppInfo", null)
                        .WithMany("AppBinaries")
                        .HasForeignKey("AppInfoId");

                    b.HasOne("Librarian.Common.Models.Db.StoreApp", "StoreApp")
                        .WithMany("StoreAppBinaries")
                        .HasForeignKey("StoreAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreApp");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Account", b =>
                {
                    b.Navigation("AppInfos");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.App", b =>
                {
                    b.Navigation("AppRunTimes");

                    b.Navigation("AppSaveFiles");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.AppInfo", b =>
                {
                    b.Navigation("AppBinaries");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Device", b =>
                {
                    b.Navigation("AppRunTimes");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeedConfig", b =>
                {
                    b.Navigation("FeedActionSets");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.FeedItemCollection", b =>
                {
                    b.Navigation("FeedConfigs");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Porter", b =>
                {
                    b.Navigation("PorterContext");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.Sentinel", b =>
                {
                    b.Navigation("SentinelLibraries");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.SentinelLibrary", b =>
                {
                    b.Navigation("AppBinaries");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.StoreApp", b =>
                {
                    b.Navigation("StoreAppBinaries");
                });

            modelBuilder.Entity("Librarian.Common.Models.Db.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("AppCategories");

                    b.Navigation("AppInfos");

                    b.Navigation("AppSaveFileCapacities");

                    b.Navigation("Apps");

                    b.Navigation("Sentinels");
                });
#pragma warning restore 612, 618
        }
    }
}
