name: .NET integration test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_pass
          MYSQL_DATABASE: dev_db
          MYSQL_USER: dev_user
          MYSQL_PASSWORD: dev_pass
        ports:
          - "3306:3306"
        options: >-
          --health-cmd "mysqladmin ping -uroot -proot_pass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: >
        dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        /p:ExcludeByFile="**/*Migrations/*.cs"
        -e DB_TYPE="MySQL"
        -e DB_CONN_STR="server=localhost;port=3306;Database=dev_db;Uid=dev_user;Pwd=dev_pass;SslMode=None;"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}