# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Publish win-x64
      run: dotnet publish Librarian.Server/Librarian.Server.csproj -c Release -o publish-win-x64 --os win -a x64
    - name: Upload win-x64 Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Librarian-win-x64
        path: publish-win-x64
    - name: Publish linux-x64
      run: dotnet publish Librarian.Server/Librarian.Server.csproj -c Release -o publish-linux-x64 --os linux -a x64
    - name: Upload linux-x64 Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Librarian-linux-x64
        path: publish-linux-x64
    - name: Publish linux-musl-x64
      run: dotnet publish Librarian.Server/Librarian.Server.csproj -c Release -o publish-linux-musl-x64 --os linux -a musl-x64
    - name: Upload linux-musl-x64 Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Librarian-linux-musl-x64
        path: publish-linux-musl-x64
    - name: Publish linux-arm64
      run: dotnet publish Librarian.Server/Librarian.Server.csproj -c Release -o publish-linux-arm64 --os linux -a arm64
    - name: Upload linux-arm64 Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Librarian-linux-arm64
        path: publish-linux-arm64
